-- ═══════════════════════════════════════════════════════════
-- SEED — move the existing catalogue out of JS and into Postgres.
-- Idempotent: re-running will not duplicate rows.
-- ═══════════════════════════════════════════════════════════

-- ── GUIDES ──────────────────────────────────────────────
insert into public.guides (slug, name, years_exp, rating, reviews, specialities, languages, active)
values
  ('grace-wanjiku', 'Grace Wanjiku', 12, 4.97, 468, '{Wildlife Safari,Big Five,Photography}', '{en,sw}', true),
  ('james-mwangi',  'James Mwangi',  15, 4.96, 1240,'{City Walks,History,Culture}',           '{en,sw,fr}', true),
  ('ali-hassan',    'Ali Hassan',    10, 4.91, 623, '{Culture,Coastal,Spice Tours}',          '{en,sw,ar}', true),
  ('felix-massawe', 'Felix Massawe', 18, 4.94, 389, '{Mountain Trekking,Kilimanjaro}',        '{en,sw}', true),
  ('omar-salim',    'Omar Salim',    14, 4.85, 298, '{Marine,Dhow Sailing,Snorkelling}',      '{en,sw}', true)
on conflict (slug) do nothing;

-- ── TOURS ───────────────────────────────────────────────
insert into public.tours (
  slug, name, subtitle, description, category, destination, country,
  duration, group_max, price_kes, deposit_pct,
  spots_total, spots_left, rating, reviews,
  departure_date, return_date, booking_deadline,
  status, featured, image, image_thumb, tags, includes, itinerary, guide_id
)
values
(
  'masai-mara-migration-safari',
  'Masai Mara Great Migration Safari',
  '7 days across the Mara Triangle',
  'The greatest wildlife spectacle on earth. 1.5 million wildebeest crossing the Mara River, predators in pursuit, and you in a private vehicle at first light. Six nights in a luxury tented camp with full board and expert guided drives every day.',
  'safari', 'masai-mara', 'Kenya',
  '7 days · 6 nights', 8, 95000, 30,
  8, 2, 4.98, 156,
  '2026-08-14', '2026-08-21', '2026-08-13T23:59:00+03:00',
  'open', true,
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80',
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&q=70',
  '{Great Migration,Private 4×4,Big Five,Luxury Camp,Full Board}',
  '{All park & conservancy fees,Luxury tented camp × 6 nights,Full board throughout,Private 4×4 + expert guide,All internal transfers from Nairobi,Sundowners daily}',
  '[{"day":1,"title":"Nairobi → Masai Mara","desc":"Morning drive to the Mara, afternoon game drive"},
    {"day":2,"title":"Full day migration tracking","desc":"Tracking the wildebeest columns and predator action"},
    {"day":3,"title":"River crossing","desc":"Position at the Mara River crossing points"},
    {"day":4,"title":"South Mara & predators","desc":"Lion prides, cheetahs and leopards"},
    {"day":5,"title":"Maasai village","desc":"Cultural visit and traditional dinner in camp"},
    {"day":6,"title":"Final drives","desc":"Celebration sundowner on the plains"},
    {"day":7,"title":"Return to Nairobi","desc":"Dawn drive, brunch, return"}]'::jsonb,
  (select id from public.guides where slug = 'grace-wanjiku')
),
(
  'masai-mara-big-five-game-drive',
  'Masai Mara Big Five Game Drive',
  'Private sunrise drive through the Mara Triangle',
  'A private sunrise drive through the most dramatic wildlife landscape on earth. We track lion, elephant, leopard, buffalo and rhino across the Mara Triangle. Lunch in the bush, sundowner on the plains.',
  'safari', 'masai-mara', 'Kenya',
  'Full day · 10h', 6, 12500, 30,
  6, 3, 4.97, 312,
  null, null, null,
  'open', true,
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80',
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&q=70',
  '{Big Five,Private 4×4,Sunrise Start,Bush Lunch}',
  '{Private 4×4 + driver-guide,Park entry fees,Bush lunch & drinks,Sundowner,Return Nairobi transfer}',
  '[{"day":1,"title":"3:30am Nairobi pickup","desc":"Early start for the 4.5h drive"},
    {"day":1,"title":"6am enter the Mara","desc":"Arrive at first light"},
    {"day":1,"title":"Big Five tracking","desc":"Full morning game viewing"},
    {"day":1,"title":"Bush lunch","desc":"Lunch watching a waterhole"},
    {"day":1,"title":"Sundowner","desc":"Drinks at a scenic viewpoint"}]'::jsonb,
  (select id from public.guides where slug = 'grace-wanjiku')
),
(
  'nairobi-city-walking-tour',
  'Nairobi City Walking Tour',
  'History, culture and markets of the capital',
  'Nairobi''s essential walk. Parliament, KICC, Jamia Mosque, City Market, August 7th Memorial and Maasai Market — led by our resident city guide with 15 years of experience.',
  'walking', 'nairobi', 'Kenya',
  '2h 30m', 16, 0, 0,
  16, 12, 4.96, 1240,
  null, null, null,
  'open', true,
  'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=800&q=80',
  'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=400&q=70',
  '{Free Tour,History,Culture,Markets,Parliament}',
  '{Expert Wildbosses guide,Walking route map,Photography stops,Maasai Market visit}',
  '[{"day":1,"title":"9am Dedan Kimathi Statue","desc":"Meet at the independence hero statue"},
    {"day":1,"title":"Parliament & KICC","desc":"Kenya''s parliament and the KICC tower"},
    {"day":1,"title":"Jamia Mosque & City Market","desc":"Colonial mosque and market stalls"},
    {"day":1,"title":"August 7th Memorial","desc":"Memorial to the 1998 bombing victims"},
    {"day":1,"title":"Maasai Market","desc":"Authentic beadwork and crafts"}]'::jsonb,
  (select id from public.guides where slug = 'james-mwangi')
),
(
  'amboseli-elephants-kilimanjaro',
  'Amboseli Elephants & Kilimanjaro Views',
  'Overnight safari with Kilimanjaro at dawn',
  'The most photogenic safari in Kenya. Elephant herds crossing the Amboseli flats with Kilimanjaro rising above them at dawn. Overnight in a classic tented camp at the park boundary.',
  'safari', 'amboseli', 'Kenya',
  '2 days · 1 night', 8, 28000, 30,
  8, 3, 4.93, 412,
  null, null, null,
  'open', true,
  'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
  'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=70',
  '{Elephants,Kilimanjaro,Overnight,Photography}',
  '{Return Nairobi transfer,All park fees,Tented camp × 1 night,Full board × 2 days,Sunrise & sunset drives}',
  '[{"day":1,"title":"Nairobi → Amboseli","desc":"Early drive, afternoon game drive"},
    {"day":1,"title":"Overnight in camp","desc":"Dinner around the campfire"},
    {"day":2,"title":"Pre-dawn Kilimanjaro","desc":"Leave 5am for dawn light on the mountain"},
    {"day":2,"title":"Brunch & return","desc":"Drive back to Nairobi"}]'::jsonb,
  (select id from public.guides where slug = 'grace-wanjiku')
),
(
  'zanzibar-stone-town-spice-farm',
  'Zanzibar Stone Town & Spice Farm',
  'UNESCO heritage & aromatic spice gardens',
  'Arab architecture, carved doors, Swahili cuisine and spice farms where vanilla, cloves and cinnamon grow wild. We finish with a seafood lunch and a dhow trip to Prison Island.',
  'culture', 'zanzibar', 'Tanzania',
  'Full day · 8h', 12, 9500, 30,
  12, 8, 4.91, 623,
  null, null, null,
  'open', true,
  'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759?w=800&q=80',
  'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759?w=400&q=70',
  '{UNESCO,Spices,History,Seafood Lunch,Dhow Trip}',
  '{Local guide,Stone Town walk (3h),Spice Farm,Prison Island dhow trip,Seafood lunch}',
  '[{"day":1,"title":"9am Stone Town walk","desc":"3-hour walk through UNESCO-listed Stone Town"},
    {"day":1,"title":"Forodhani Gardens lunch","desc":"The famous seafood market"},
    {"day":1,"title":"Spice Farm","desc":"Vanilla, cloves and cinnamon growing wild"},
    {"day":1,"title":"Prison Island","desc":"Dhow trip to the giant tortoises"}]'::jsonb,
  (select id from public.guides where slug = 'ali-hassan')
),
(
  'diani-dhow-sunset-cruise',
  'Diani Dhow Sunset Cruise & Dolphins',
  'Traditional dhow, dolphins & reef snorkelling',
  'Drift across the Indian Ocean on a traditional dhow. Chase spinner dolphins, snorkel the coral reef, and drift home as the sun sets over the horizon.',
  'beach', 'diani', 'Kenya',
  '3h', 14, 5500, 30,
  14, 8, 4.85, 298,
  null, null, null,
  'open', true,
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=70',
  '{Sunset,Dhow,Dolphins,Reef Snorkel}',
  '{Dhow charter,Snorkel gear,Life jackets,Drinks & coconut,Dolphin spotting}',
  '[{"day":1,"title":"4pm Diani jetty","desc":"Board the traditional wooden dhow"},
    {"day":1,"title":"Dolphin encounter","desc":"Offshore to find spinner dolphin pods"},
    {"day":1,"title":"Reef snorkel","desc":"Anchor at the coral reef"},
    {"day":1,"title":"Sundowner sail","desc":"Drinks as the sun sets"}]'::jsonb,
  (select id from public.guides where slug = 'omar-salim')
),
(
  'kilimanjaro-marangu-route-6-days',
  'Kilimanjaro — Marangu Route 6 Days',
  'Africa''s highest peak — 89% summit success rate',
  'Africa''s highest peak at 5,895m. Our Marangu route has an 89% summit success rate. We provide everything — porters, all meals, acclimatisation days, and a certified guide with 400+ successful summits.',
  'adventure', 'kilimanjaro', 'Tanzania',
  '6 days · 5 nights', 8, 185000, 30,
  8, 6, 4.94, 389,
  '2026-09-15', '2026-09-20', '2026-09-10T23:59:00+03:00',
  'open', true,
  'https://images.unsplash.com/photo-1519923834699-ef0b7cde4712?w=800&q=80',
  'https://images.unsplash.com/photo-1519923834699-ef0b7cde4712?w=400&q=70',
  '{Summit 5895m,89% Success,Porters Included,All Meals,Certificate}',
  '{All KINAPA park fees,Hut accommodation × 5 nights,All meals on mountain,Porters × 2 per climber,Certified mountain guide,Summit certificate,Rescue deposit}',
  '[{"day":1,"title":"Moshi briefing","desc":"Gear check and briefing, overnight hotel"},
    {"day":2,"title":"Mandara Huts 2,720m","desc":"Trek through rainforest, 5-7h"},
    {"day":3,"title":"Horombo Huts 3,720m","desc":"Moorland and giant heather, 6-8h"},
    {"day":4,"title":"Kibo Huts 4,700m","desc":"Alpine desert, acclimatisation walk"},
    {"day":5,"title":"Uhuru Peak 5,895m","desc":"Midnight start, summit, descend to Horombo"},
    {"day":6,"title":"Descent & Moshi","desc":"Marangu Gate, certificate presentation"}]'::jsonb,
  (select id from public.guides where slug = 'felix-massawe')
)
on conflict (slug) do nothing;
